version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: server-prod
    ports:
      - '5000:5000'
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: client-prod
    ports:
      - '8080:80'
    depends_on:
      - server
    environment:
      - NODE_ENV=production
